name: Setup Go Environment
description: "Set up Go and dependencies for CI"

inputs:
  github-token:
    description: "GitHub token for private repo access"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: ${{ env.GO_VERSION || '1.21' }}
        cache: true
        check-latest: true

    - name: Configure Git for private repos
      if: inputs.github-token != ''
      run: |
        git config --global url."https://x-access-token:${{ inputs.github-token }}@github.com/descope".insteadOf "https://github.com/descope"
      shell: bash

    - name: Download and vendor dependencies
      run: |
        echo "Attempting to download dependencies..."
        if ! go mod download; then
          echo "⚠️ Some private dependencies are not accessible"
          echo "This is expected if the GitHub App doesn't have access to all repositories"
          echo "Continuing with available dependencies..."
        fi

        echo "Creating vendor directory..."
        if ! go mod vendor; then
          echo "⚠️ Vendoring failed, some dependencies may be missing"
          echo "This may cause build failures if missing dependencies are required"
        fi
      shell: bash
      env:
        GOPRIVATE: github.com/descope/*
