name: Setup Go Environment
description: "Set up Go and dependencies for CI"

inputs:
  github-token:
    description: "GitHub token for private repo access"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: ${{ env.GO_VERSION || '1.21' }}
        cache: true
        check-latest: true

    - name: Configure Git for private repos
      if: inputs.github-token != ''
      run: |
        git config --global url."https://x-access-token:${{ inputs.github-token }}@github.com/descope".insteadOf "https://github.com/descope"
      shell: bash

    - name: Download and vendor dependencies
      run: |
        go mod download
        go mod vendor
      shell: bash
      env:
        GOPRIVATE: github.com/descope/*
