// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: authzcache.proto

package v1

import (
	v1 "github.com/descope/authzservice/pkg/authzservice/proto/v1"
	_ "github.com/descope/protoc-gen-mocker/mocker"
	_ "github.com/descope/protoc-gen-validate/proto"
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_authzcache_proto protoreflect.FileDescriptor

const file_authzcache_proto_rawDesc = "" +
	"\n" +
	"\x10authzcache.proto\x12\bauthzcv1\x1a\x1cgoogle/api/annotations.proto\x1a\fmocker.proto\x1a\x1bopenapiv3/annotations.proto\x1a\x0evalidate.proto\x1a\x0ev1/authz.proto2\xb2\b\n" +
	"\n" +
	"AuthzCache\x12\x85\x02\n" +
	"\x0fCreateFGASchema\x12\x1d.authzv1.SaveDSLSchemaRequest\x1a\x1e.authzv1.SaveDSLSchemaResponse\"\xb2\x01\xbaG\x90\x01\x12\x1bCreate the given FGA Schema\x1a\x1cCreate the given FGA Schema.*\x0fCreateFGASchemaZ\x1a\n" +
	"\x18\n" +
	"\x14AuthProjectIdMgmtKey\x12\x00j\x16\n" +
	"\rx-publishYaml\x12\x05\x12\x03fgaj\x0e\n" +
	"\ax-order\x12\x03\x12\x011\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/mgmt/fga/schema\x12\x8a\x02\n" +
	"\x12CreateFGARelations\x12\x1c.authzv1.CreateTuplesRequest\x1a\x1d.authzv1.CreateTuplesResponse\"\xb6\x01\xbaG\x91\x01\x12\x1aCreate the given relations\x1a\x1bCreate the given relations.*\x12CreateFGARelationsZ\x1a\n" +
	"\x18\n" +
	"\x14AuthProjectIdMgmtKey\x12\x00j\x16\n" +
	"\rx-publishYaml\x12\x05\x12\x03fgaj\x0e\n" +
	"\ax-order\x12\x03\x12\x012\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/mgmt/fga/relations\x12\x91\x02\n" +
	"\x12DeleteFGARelations\x12\x1c.authzv1.DeleteTuplesRequest\x1a\x1d.authzv1.DeleteTuplesResponse\"\xbd\x01\xbaG\x91\x01\x12\x1aDelete the given relations\x1a\x1bDelete the given relations.*\x12DeleteFGARelationsZ\x1a\n" +
	"\x18\n" +
	"\x14AuthProjectIdMgmtKey\x12\x00j\x16\n" +
	"\rx-publishYaml\x12\x05\x12\x03fgaj\x0e\n" +
	"\ax-order\x12\x03\x12\x013\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/mgmt/fga/relations/delete\x12\xfa\x01\n" +
	"\x05Check\x12\x15.authzv1.CheckRequest\x1a\x16.authzv1.CheckResponse\"\xc1\x01\xbaG\xa0\x01\x12(Check if the given relations are allowed\x1a)Check if the given relations are allowed.*\x05CheckZ\x1a\n" +
	"\x18\n" +
	"\x14AuthProjectIdMgmtKey\x12\x00j\x16\n" +
	"\rx-publishYaml\x12\x05\x12\x03fgaj\x0e\n" +
	"\ax-order\x12\x03\x12\x013\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/mgmt/fga/checkBw\xba~=\b\x01\"\fgrpcauthzcv1*\x10authzcacheclient2\x19pkg/authzcache/test/mocksZ5github.com/descope/authzcache/pkg/authzcache/proto/v1b\x06proto3"

var file_authzcache_proto_goTypes = []any{
	(*v1.SaveDSLSchemaRequest)(nil),  // 0: authzv1.SaveDSLSchemaRequest
	(*v1.CreateTuplesRequest)(nil),   // 1: authzv1.CreateTuplesRequest
	(*v1.DeleteTuplesRequest)(nil),   // 2: authzv1.DeleteTuplesRequest
	(*v1.CheckRequest)(nil),          // 3: authzv1.CheckRequest
	(*v1.SaveDSLSchemaResponse)(nil), // 4: authzv1.SaveDSLSchemaResponse
	(*v1.CreateTuplesResponse)(nil),  // 5: authzv1.CreateTuplesResponse
	(*v1.DeleteTuplesResponse)(nil),  // 6: authzv1.DeleteTuplesResponse
	(*v1.CheckResponse)(nil),         // 7: authzv1.CheckResponse
}
var file_authzcache_proto_depIdxs = []int32{
	0, // 0: authzcv1.AuthzCache.CreateFGASchema:input_type -> authzv1.SaveDSLSchemaRequest
	1, // 1: authzcv1.AuthzCache.CreateFGARelations:input_type -> authzv1.CreateTuplesRequest
	2, // 2: authzcv1.AuthzCache.DeleteFGARelations:input_type -> authzv1.DeleteTuplesRequest
	3, // 3: authzcv1.AuthzCache.Check:input_type -> authzv1.CheckRequest
	4, // 4: authzcv1.AuthzCache.CreateFGASchema:output_type -> authzv1.SaveDSLSchemaResponse
	5, // 5: authzcv1.AuthzCache.CreateFGARelations:output_type -> authzv1.CreateTuplesResponse
	6, // 6: authzcv1.AuthzCache.DeleteFGARelations:output_type -> authzv1.DeleteTuplesResponse
	7, // 7: authzcv1.AuthzCache.Check:output_type -> authzv1.CheckResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authzcache_proto_init() }
func file_authzcache_proto_init() {
	if File_authzcache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authzcache_proto_rawDesc), len(file_authzcache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authzcache_proto_goTypes,
		DependencyIndexes: file_authzcache_proto_depIdxs,
	}.Build()
	File_authzcache_proto = out.File
	file_authzcache_proto_goTypes = nil
	file_authzcache_proto_depIdxs = nil
}
