// Code generated by protoc-gen-validate. DO NOT EDIT.
// version: 1.6.5
// source: authzcache.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/descope/protoc-gen-validate/utils"
	"github.com/descope/protoc-gen-validate/validate"
)

// Ensure all the imports are used
var (
	_ = bytes.MinRead
	_ = errors.Is
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = sort.Sort
	_ = utils.ValidateField
	_ = validate.Version
)

// AuthzCache metadata - this should move to some other place at some point...
var AuthzCacheMetadata = &_AuthzCacheMetadata{
	AllMethods: _AuthzCacheAllMethods,
	Methods: &_AuthzCacheMethods{
		CreateFGASchema:     _AuthzCacheAllMethods[0],
		CreateFGARelations:  _AuthzCacheAllMethods[1],
		DeleteFGARelations:  _AuthzCacheAllMethods[2],
		Check:               _AuthzCacheAllMethods[3],
		WhoCanAccess:        _AuthzCacheAllMethods[4],
		WhatCanTargetAccess: _AuthzCacheAllMethods[5],
	},
}

var _AuthzCacheAllMethods = []*validate.MethodMetadata{
	{Name: "CreateFGASchema", Path: "/authzcv1.AuthzCache/CreateFGASchema"},
	{Name: "CreateFGARelations", Path: "/authzcv1.AuthzCache/CreateFGARelations"},
	{Name: "DeleteFGARelations", Path: "/authzcv1.AuthzCache/DeleteFGARelations"},
	{Name: "Check", Path: "/authzcv1.AuthzCache/Check"},
	{Name: "WhoCanAccess", Path: "/authzcv1.AuthzCache/WhoCanAccess"},
	{Name: "WhatCanTargetAccess", Path: "/authzcv1.AuthzCache/WhatCanTargetAccess"},
}

type _AuthzCacheMetadata struct {
	AllMethods []*validate.MethodMetadata
	Methods    *_AuthzCacheMethods
}

type _AuthzCacheMethods struct {
	CreateFGASchema     *validate.MethodMetadata
	CreateFGARelations  *validate.MethodMetadata
	DeleteFGARelations  *validate.MethodMetadata
	Check               *validate.MethodMetadata
	WhoCanAccess        *validate.MethodMetadata
	WhatCanTargetAccess *validate.MethodMetadata
}
