name: Security
description: "Run security checks"

runs:
  using: "composite"
  steps:
    - name: Auth Setup
      id: auth
      uses: ./.github/actions/auth-setup
      env:
        RELEASE_APP_ID: ${{ env.RELEASE_APP_ID }}
        RELEASE_APP_PEM: ${{ env.RELEASE_APP_PEM }}

    - name: Setup Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Download dependencies
      env:
        GOPRIVATE: github.com/descope/*
      run: |
        go mod download
        go mod verify
      shell: bash

    - name: Run security checks
      env:
        GOPRIVATE: github.com/descope/*
      run: |
        echo "Installing gosec..."
        go install github.com/securecodewarrior/gosec/v2/cmd/gosec@latest

        echo "Running gosec security scanner..."
        gosec ./...

        echo "Security checks completed"
      shell: bash
