name: Run Security Checks
description: "Run Security Checks"

runs:
  using: "composite"
  steps:
    - name: Setup Go
      if: ${{ hashFiles('go.mod') != '' }}
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version-file: go.mod
        cache: true
        check-latest: true
    - name: Setup NodeJS if package.json exists
      if: ${{ hashFiles('package.json') != '' }}
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: package.json
    - if: ${{ hashFiles('package.json') != '' }}
      name: Install NodeJS dependencies
      shell: bash
      run: |
        corepack enable
        if [ -f "yarn.lock" ]; then
          yarn install --immutable
        elif [ -f "pnpm-lock.yaml" ]; then
          pnpm install --frozen-lockfile
        else
          npm ci
        fi
    - if: ${{ hashFiles('package.json') != '' }}
      name: Run Node Security Checks
      shell: bash
      run: |
        npm audit signatures
