name: Run Security Checks
description: "Run Security Checks"

inputs:
  go_version:
    description: "Go version to use"
    required: true
  scripts_folder:
    description: "Scripts folder"
    required: false
    default: "."
  APP_PEM:
    description: "Github App Key"
    required: true
  APP_ID:
    description: "Github App ID"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Go
      if: ${{ hashFiles('go.mod') != '' }}
      uses: ./.github/actions/setup
      with:
        go_version: ${{ inputs.go_version }}
        APP_PEM: ${{ inputs.APP_PEM }}
        APP_ID: ${{ inputs.APP_ID }}
    - name: Setup NodeJS if package.json exists
      if: ${{ hashFiles('package.json') != '' }}
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: package.json
    - if: ${{ hashFiles('package.json') != '' }}
      name: Install NodeJS dependencies
      shell: bash
      run: |
        corepack enable
        if [ -f "yarn.lock" ]; then
          yarn install --immutable
        elif [ -f "pnpm-lock.yaml" ]; then
          pnpm install --frozen-lockfile
        else
          npm ci
        fi
    - if: ${{ hashFiles('package.json') != '' }}
      name: Run Node Security Checks
      shell: bash
      run: |
        npm audit signatures
