name: Lint
description: "Run Go linting and security checks"

runs:
  using: "composite"
  steps:
    - name: Auth Setup
      id: auth
      uses: ./.github/actions/auth-setup
      env:
        RELEASE_APP_ID: ${{ env.RELEASE_APP_ID }}
        RELEASE_APP_PEM: ${{ env.RELEASE_APP_PEM }}

    - name: Setup Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version-file: go.mod
        cache: true

    - name: Download dependencies
      env:
        GOPRIVATE: github.com/descope/*
      run: |
        go mod download
        go mod verify
      shell: bash

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@8564da7cb3c6866ed1da648ca8f00a258ef0c802 # v6.5.2
      with:
        version: v2.11.4
        install-mode: goinstall
        args: --config=./scripts/lint/.golangci.yml

    - name: Run go vet
      env:
        GOPRIVATE: github.com/descope/*
      run: go vet ./...
      shell: bash

    - name: Check formatting
      env:
        GOPRIVATE: github.com/descope/*
      run: |
        if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
          echo "Files not formatted properly:"
          gofmt -l .
          exit 1
        fi
      shell: bash
