name: Lint and more checks
description: "Lint and more checks"
inputs:
  go_version:
    description: "Go version to use"
    required: true
  scripts_folder:
    description: "Scripts folder"
    required: false
    default: "."
  APP_PEM:
    description: "Github App Key"
    required: true
  APP_ID:
    description: "Github App ID"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup
      id: setup
      uses: descope/common/.github/actions/setup@main
      with:
        go_version: ${{ inputs.go_version }}
        APP_PEM: ${{ inputs.APP_PEM }}
        APP_ID: ${{ inputs.APP_ID }}

    - name: Run golangci-lint
      uses: reviewdog/action-golangci-lint@f9bba13753278f6a73b27a56a3ffb1bfda90ed71 # v2.8.0
      env:
        TAR_OPTIONS: --skip-old-files
      with:
        github_token: ${{ steps.setup.outputs.token }}
        fail_level: any
        fail_on_error: true
        golangci_lint_flags: "--config=${{ inputs.scripts_folder }}/scripts/lint/.golangci.yml"
        filter_mode: nofilter
        reporter: github-check
        golangci_lint_version: v1.64.8 # v2 has breaking changes, duh.

    - name: Run leaks and additional checks
      env:
        TOKEN: ${{ steps.setup.outputs.token }}
      run: |
        chmod +x ${{ inputs.scripts_folder }}/build/ci/build_lint.sh
        ${{ inputs.scripts_folder }}/build/ci/build_lint.sh
      shell: bash
